### ISSUE TITLE
Offline Maps

### ISSUE THREAD

**Issue by ghost** [GlobalcachingEU/GSAKWrapper#16]
When a cache is clicked/double-clicked on the map, I was expecting it to be selected back in GSAK as per the video, but this is not happening. Is there anything I can check to see if it is set up correctly?

**Comment by RobertoPeters** [comment]
I am not sure if this is also for the offline map, but at least for the online map it works like that.
However, it will only select the geocache in GSAK if the GSAKWrapper is started manually (not within GSAK). This is because selecting a geocaches in GSAK is done by calling GSAK with parameters. And the geocaches will not be selected if a macro is ative.

**Comment by RobertoPeters** [comment]
I will check if the offline map selects the geocaches in GSAK (if not ran within GSAK)

**Comment by ghost** [comment]
Just tried starting the wrapper up manually but it is still not selecting caches in GSAK.

**Comment by RobertoPeters** [comment]
thanks for testing and reporting. I will fix this (for offline maps).

**Comment by ghost** [comment]
Two observations for the future. It would be nice to have options on the map to disable clustering and the cache labels.

**Comment by RobertoPeters** [comment]
The issue itself 
(When a cache is clicked/double-clicked on the map, I was expecting it to be selected back in GSAK as per the video, but this is not happening. Is there anything I can check to see if it is set up correctly?)

has been fixed in version V1.0.0.0 (note that it only selects the geocaches if started next to GSAK and not by a macro)

The other requests
(Two observations for the future. It would be nice to have options on the map to disable clustering and the cache labels.)
is another seperate issue
