### ISSUE TITLE
Requested features

### ISSUE THREAD

**Issue by Khoda1** [GlobalcachingEU/GSAKWrapper#6]
A basic instruction manual
Add miles

Include custom database fields. I have added a number of extra fields.
These are custom GSAK fields that I have added. Example might be reviewer. I have also added several that have check boxes for yes/no answers. Not all are showing up in the list.

Allow locations that have been defined by name in GSAK. Such as Home.
What can I do with the exported flow sequence? Can I use it to create a macro or search filter?
Auto arrange the flow chart when adding a new block in the middle.
Allow selecting several blocks so they can be moved as a unit. This is useful for realigning the blocks after adding one in the middle.

I suspect that while several of the requests seem simple to me the programming will be lengthy.

**Comment by RobertoPeters** [comment]
I lot of issues stated in one. Maybe the next time add them seperatly so we can track the status. Otherwise items in this list might get forgotten.

A basic instruction manual

> A wiki has been started on this website (github) and there is a video. This is just a start and I agree that it should be extended. But I will first focus on functionalitey and more videos.

Include custom database fields. I have added a number of extra fields.

> They are included.

Allow locations that have been defined by name in GSAK. Such as Home.

> Good point, will be added

What can I do with the exported flow sequence? Can I use it to create a macro or search filter?

> Yes. I will create a video to show you how. However, version V0.1.0.0 has an error that copies the file to a protected folder. This will be fixed in V0.2.0.0

Auto arrange the flow chart when adding a new block in the middle.
Allow selecting several blocks so they can be moved as a unit. This is useful for realigning the blocks after adding one in the middle

> Tricky, because that would take some programming. But it is on the list todo (just nog a high priority)

**Comment by Khoda1** [comment]
I can resubmit let me know

**Comment by RobertoPeters** [comment]
No, its ok.
Just for future reference ;-)

**Comment by taybee** [comment]
thanks for the GSAKwrapper  it looking good 
1.    What about a display box to show the answers in  so you do not have to open GSAK up 

or

  2 Add a drop down for Views in GSAk   

or  both would be great

**Comment by RobertoPeters** [comment]
taybee, please submit new issues and assign the correct label (request in this case).

What about a display box to show the answers in so you do not have to open GSAK up

> What do you mean with Displaybox? You do not have to open GSAK in order to use the wrapper. More actions will be added for daily tasks such as export to GPX.

Add a drop down for Views in GSAk

> What do you mean?

But please open new issues for these, otherwise these remarks wmight get forgotten.
